### ISSUE TITLE
master branch to be migrated to 0.5.0 version

### ISSUE THREAD

**Issue by vsch** [vsch/kotlin-jdbc#12]
Version 0.5.0 currently in dev-0.5.0 branch has many improvements over the old implementation. 

Although it has many **breaking changes**, migrating code is not complicated because it consists mostly of deleting extra arguments to model functions and adding a session argument to model constructor when not using the default session.

The model instance is now associated with a session and carries with it all the data extraction information reducing the noise in the code. See: https://github.com/vsch/kotlin-jdbc/blob/dev-0.5.0/README.md

Scripts for generating models were also greatly improved to reduce and in most cases eliminate the need for manual editing. An optional `model-config.json` file defines the mapping of models to generated file names, directory location and package for a project.

Overall, the pain of migrating code is worth the gain in convenience.

Most likely the next 0.4.12 version will be the last update to 0.4.0 branch

**Comment by jontro** [comment]
Any timeline for the 0.5.0 release? Looking at a replacement for spring JdbcTemplate

**Comment by vsch** [comment]
@jontro, I will add a release of this for end of this week. 

I dropped the ball on this project because I have been working around the clock on  flexmark-java and Markdown Navigator plugin for JetBrains IDEs. The latter was broken by a latest release of the IDE, in a way that required major surgery to replace a broken library.

I added a due date for this coming Sunday so it will be done by Monday.

**Comment by jontro** [comment]
Just asking :) Thanks for taking the time working on open source!

**Comment by vsch** [comment]
@jontro, it is good to ask. It lets me know that someone needs a release. Otherwise, I feel like it's only me and for that I have my local dev build so going through the trouble of a release gets low priority.

I will take the time to make a release this weekend.

**Comment by vsch** [comment]
@jontro, Repo updated, maven updated but may take a while to show up in maven central.
