### ISSUE TITLE
Make Session an interface for easy decoration

### ISSUE THREAD

**Issue by root-talis** [vsch/kotlin-jdbc#2]
I have ran into a situation when I need to do two things:

1. Log all queries - for debug;
2. Make queries frequency report - for throughput monitoring, queries per second.

The most straightforward way to implement his would be to wrap the Session object into a decorator. In order to use Kotlin decoration syntax, both the original Session class and the decorator need to implement the same interface.

**Comment by vsch** [comment]
@root-talis, good idea. 

* Fix: factor out `Session` and `Transaction` functions into interfaces. Implementation renamed
  to `SessionImpl` and `TransactionImpl`

I will be making a release 0.4.2 with these changes.

**Comment by vsch** [comment]
@root-talis, repo updated. Maven update done but will take some time to propagate.

**Comment by root-talis** [comment]
Thanks for the update! Works like a charm :)
