### ISSUE TITLE
did you consider sending upstream to kotliquery?

### ISSUE THREAD

**Issue by pabl0rg** [vsch/kotlin-jdbc#5]
Hello,  this seems pretty cool but it would be valuable to work alongside the creator of Kotliquery since he has years of experience with scalikejdbc.  Did you try to get your changes into Kotliquery?

Best,
Juan

**Comment by vsch** [comment]
@pabl0rg, I did not because the changes are fairly significant and I did not see it as an evolution of Kotliquery but a major rewrite which is not compatible with Kotliquery.
